version: '3.9'

services:
  nginx:
    build:
        context: .
        dockerfile: nginx.dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../src:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/custom.cnf
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ../src:/var/www/html:delegated
