version: '3.9'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../src:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/custom.cnf
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ../src:/var/www/html:delegated